
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

rest_command:
  airtable_log:
    url: "https://api.airtable.com/v0/appeuWmWqkkoGjuQL/tblZGNXgyVU8ieHCo"
    method: POST
    headers:
      Authorization: !secret airtable_token
      Content-Type: "application/json"
    payload: >
      {"fields": {"Name": "Union Square", "date": "{{ now() }}"}}
